"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # 👈 新增：引入讀取環境變數的工具

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ⭐ 關鍵步驟：載入 .env 檔案
# 這行會去讀取您專案根目錄下的 .env 檔案內容
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ⭐ 安全修正 1：不再寫死，改從 .env 讀取
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# ⭐ 安全修正 2：從 .env 判斷是否開啟除錯模式
# 如果 .env 裡寫 DEBUG=True，這裡就會是 True
DEBUG = os.getenv('DEBUG') == 'True'

# 開發階段允許所有網域連線，方便測試
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方套件
    'django_summernote',

    # --- My Apps ---
    'core',
    'tools',
    'users',
    'tutorials',
    'labs', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'zh-hant'
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_TZ = True


# === Static files (CSS, JS, Images) ===
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# === Media files (User Uploads) ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# === Login / Logout Redirects ===
LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'dashboard' 
LOGOUT_REDIRECT_URL = 'home'


# === API Keys (安全性升級版) ===
# ⭐ 安全修正 3：從環境變數讀取 AI Key，不再直接顯示於程式碼中
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# 安全檢查：啟動時檢查是否成功讀取
if not GEMINI_API_KEY:
    print("⚠️  警告：找不到 GEMINI_API_KEY！請檢查您的 .env 檔案設定。")
else:
    # 只印出前 10 碼確認，避免洩漏完整 Key
    print(f"🔥 系統防禦啟動：已從保險箱載入 AI 核心鑰匙 -> {GEMINI_API_KEY[:10]}...")