# Generated by Django 6.0 on 2026-01-05 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='Uncategorized', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users_who_favorited', models.ManyToManyField(blank=True, related_name='favorite_tools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
