# Generated by Django 6.0 on 2026-01-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='users_who_favorited',
            new_name='favorites',
        ),
    ]
