# Generated by Django 6.0 on 2026-01-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_rename_users_who_favorited_tool_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='favorites',
        ),
    ]
