# Generated by Django 6.0 on 2026-01-06 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_tool_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
