# Generated by Django 6.0 on 2026-01-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='瀏覽次數'),
        ),
    ]
