# Generated by Django 6.0 on 2026-01-08 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_tool_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='saved_tools', to=settings.AUTH_USER_MODEL, verbose_name='收藏的使用者'),
        ),
    ]
