# Generated by Django 6.0 on 2026-01-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='實驗標題')),
                ('description', models.TextField(verbose_name='實驗心得')),
                ('cover_image', models.ImageField(upload_to='lab_covers/', verbose_name='成果封面圖')),
                ('prompt_text', models.TextField(blank=True, verbose_name='使用的 Prompt 咒語')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.tool', verbose_name='使用工具')),
            ],
            options={
                'verbose_name': '實驗專案',
                'verbose_name_plural': '實驗專案',
            },
        ),
    ]
