# Generated by Django 6.0 on 2026-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labproject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lab_videos/', verbose_name='成果影片'),
        ),
    ]
