# Generated by Django 6.0 on 2026-01-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_labproject_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labproject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_covers/', verbose_name='成果封面圖'),
        ),
    ]
