# Generated by Django 6.0 on 2026-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_labproject_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='labproject',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='瀏覽次數'),
        ),
    ]
