# Generated by Django 6.0 on 2026-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_labproject_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='labproject',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_before/', verbose_name='Before 對比圖 (線稿/原圖)'),
        ),
        migrations.AddField(
            model_name='labproject',
            name='negative_prompt',
            field=models.TextField(blank=True, help_text='例如: low quality, blurry, nsfw', verbose_name='負向 Prompt (Negative)'),
        ),
        migrations.AlterField(
            model_name='labproject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_covers/', verbose_name='成果封面圖 (After)'),
        ),
    ]
