# Generated by Django 6.0 on 2026-01-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_labproject_before_image_labproject_negative_prompt_and_more'),
        ('tools', '0008_alter_tool_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labproject',
            name='related_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_projects', to='tools.tool', verbose_name='使用工具'),
        ),
    ]
