# Generated by Django 6.0 on 2026-01-15 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_alter_labproject_related_tool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labproject',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='完整文章內容'),
        ),
        migrations.AddField(
            model_name='labproject',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('completed', '完成')], default='draft', max_length=20, verbose_name='狀態'),
        ),
        migrations.AddField(
            model_name='labproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
    ]
