# Generated by Django 6.0 on 2026-01-19 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_labproject_content_labproject_status_labproject_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reverse_engineering/', verbose_name='上傳圖片')),
                ('prompt_result', models.TextField(blank=True, verbose_name='AI 分析出的咒語')),
                ('analysis_report', models.TextField(blank=True, verbose_name='詳細分析報告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '逆向工程紀錄',
                'verbose_name_plural': '逆向工程紀錄',
            },
        ),
    ]
