# Generated by Django 6.0 on 2026-01-20 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_reverseimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ISO 11608 分析報告', max_length=200, verbose_name='報告標題')),
                ('data_file', models.FileField(upload_to='iso_data/', verbose_name='數據檔案')),
                ('result_plot', models.ImageField(blank=True, null=True, upload_to='iso_plots/', verbose_name='分析圖表')),
                ('report_content', models.TextField(blank=True, verbose_name='分析數據內容')),
                ('is_pass', models.BooleanField(default=False, verbose_name='是否通過')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISO分析紀錄',
                'verbose_name_plural': 'ISO分析紀錄',
            },
        ),
    ]
