# Generated by Django 6.0 on 2026-01-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_isoanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isoanalysis',
            name='report_content',
        ),
        migrations.AddField(
            model_name='isoanalysis',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='詳細分析數據'),
        ),
    ]
