# Generated by Django 6.0 on 2026-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_remove_isoanalysis_report_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isoanalysis',
            name='density',
            field=models.FloatField(default=1.0, verbose_name='液體密度 (g/cm³)'),
        ),
        migrations.AddField(
            model_name='isoanalysis',
            name='param_alpha',
            field=models.FloatField(default=0.01, verbose_name='解析度 α (mL)'),
        ),
        migrations.AddField(
            model_name='isoanalysis',
            name='param_beta',
            field=models.FloatField(default=5.0, verbose_name='公差範圍 β (%)'),
        ),
        migrations.AddField(
            model_name='isoanalysis',
            name='param_k',
            field=models.FloatField(default=2.92, verbose_name='ISO K-Factor'),
        ),
        migrations.AddField(
            model_name='isoanalysis',
            name='v_max',
            field=models.FloatField(default=0.5, verbose_name='最大劑量 Max'),
        ),
        migrations.AddField(
            model_name='isoanalysis',
            name='v_mid',
            field=models.FloatField(default=0.3, verbose_name='中間劑量 Mid'),
        ),
        migrations.AddField(
            model_name='isoanalysis',
            name='v_min',
            field=models.FloatField(default=0.1, verbose_name='最小劑量 Min'),
        ),
    ]
